// GRIDBALANCE platform API: REST + WebSocket, SQLite (node:sqlite), role-based auth, alarm engine, SCADA ingest.
import http from 'node:http';import crypto from 'node:crypto';import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';import {WebSocketServer} from 'ws';
const PORT=+process.env.PORT||3000,SPEED=+process.env.SPEED||1,SECRET=process.env.SECRET||'dev-secret-change-me',KEY=process.env.SCADA_KEY||'scada-demo-key',PASS=process.env.DEMO_PASSWORD||'demo';
const LIM=30,WARN=24,STALE_S=5; // minutes (simulated: SPEED sim-min per real second) / seconds without telemetry
const r1=v=>Math.round(v*10)/10,mins=ms=>ms/1000*SPEED;
fs.mkdirSync('data',{recursive:true});const db=new DatabaseSync(process.env.DB||'data/gridbalance.db');
db.exec(`create table if not exists users(name text primary key,hash text,role text,scope text);
create table if not exists feeders(id text primary key,bcc text,crc text,mw real,meas real,prio int,crit int,state text,o real,cum real,rot int,ens real,al int,seen real,cmd text,city int,plan real);
create table if not exists orders(id integer primary key autoincrement,ts real,by text,mw real,mode text,status text,first_open real,flex real default 0,am text);
create table if not exists alloc(oid int,level text,name text,mw real,primary key(oid,level,name));
create table if not exists events(id integer primary key autoincrement,ts real,actor text,role text,action text,detail text);
create table if not exists cities(id int primary key,name text,bcc text,pop int,dem real,pr int);
create table if not exists hist(id integer primary key autoincrement,city int,d int,du real,cons int);
create table if not exists flex(id text primary key,name text,cur real,mw real,dur real,state text,omw real,odur real,msg text);
create table if not exists alerts(id integer primary key autoincrement,city int,oid int,feeder text,ts real,start real,status text);
create table if not exists citizens(user text primary key,name text,channel text);`);
const Q=(s,...a)=>db.prepare(s).all(...a),G=(s,...a)=>db.prepare(s).get(...a),R=(s,...a)=>db.prepare(s).run(...a);
const hash=(p,s=crypto.randomBytes(8).toString('hex'))=>s+':'+crypto.scryptSync(p,s,16).toString('hex');
for(const a of ["alter table feeders add column est real","alter table events add column oid int","alter table events add column h text"])try{db.exec(a)}catch(e){}
db.exec(`create table if not exists sites(id integer primary key autoincrement,name text,type text,feeder text,by text,ts real);create table if not exists perf(oid int,bcc text,target real,planned real,actual real,primary key(oid,bcc));`);
const BCCS=[['Tunis','North'],['Grombalia','North'],['Sousse','North'],['Beja','North'],['Gafsa','South'],['Sfax','South'],['Gabes','South']]; // as in STEG's manual load-shedding document
if(!G('select 1 x from users')){const U=[['dn','DN',''],['admin','ADMIN',''],['crc_north','CRC','North'],['crc_south','CRC','South'],...BCCS.map(b=>['bcc_'+b[0].toLowerCase(),'BCC',b[0]])];
 U.forEach(u=>R('insert into users values(?,?,?,?)',u[0],hash(PASS),u[1],u[2]));
 BCCS.forEach((b,i)=>{for(let k=0;k<14;k++)R('insert into feeders(id,bcc,crc,mw,meas,prio,crit,state,o,cum,rot,ens,al,seen,cmd,city,plan) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)','F-'+((i+1)*100+k+1),b[0],b[1],r1(6+((i*7+k*5)%9)*1.3),0,1+(k*3+i)%5,k==13?1:0,'CLOSED',null,0,0,0,0,Date.now(),null,i*4+(k%4),null)});
 R('update feeders set meas=mw');seedMore()}
function seedMore(){const L='ABCDEFGHIJKLMNOPQRSTUVWXYZ',nm=i=>i<26?L[i]:'A'+L[i-26];for(let i=0;i<28;i++){const dem=r1(Q('select sum(mw) s from feeders where city=?',i)[0].s*2.2),pop=20000+((i*37)%11)*9000;R('insert into cities values(?,?,?,?,?,?)',i,'City '+nm(i),BCCS[i>>2][0],pop,dem,Math.min(5,1+(i*3)%5));for(let k=0;k<1+(i*3)%5;k++)R('insert into hist(city,d,du,cons) values(?,?,?,?)',i,2+(k*4+i*3)%20,20+(k*13+i*17)%50,Math.round(pop*.3))}
 [['Factory A',12,30,30],['Factory B',20,45,20],['Factory C',12,28,45]].forEach((x,i)=>R("insert into flex values(?,?,?,?,?,'Available',null,null,'')",'ind_'+'abc'[i],x[0],x[2],x[1],x[3]));
 ['ind_a','ind_b','ind_c'].forEach(n=>R('insert into users values(?,?,?,?)',n,hash(PASS),'IND',n));
 [['cit_sami',8,'App + SMS','Sami B.'],['cit_amel',20,'SMS','Amel K.']].forEach(c=>{R('insert into users values(?,?,?,?)',c[0],hash(PASS),'CIT',String(c[1]));R('insert into citizens values(?,?,?)',c[0],c[3],c[2])})}
function seedSites(){const T=[['Hospital','Regional Hospital'],['Civil protection','Civil Protection HQ'],['Water station','Water Pumping Station'],['Police','Police Operations Center']];Q('select * from feeders where crit=1').forEach(f=>T.forEach(t=>R('insert into sites(name,type,feeder,by,ts) values(?,?,?,?,?)',`${t[1]} (${f.bcc})`,t[0],f.id,'system',Date.now())))}
if(!G('select 1 x from sites'))seedSites();
const learnFactor=b=>{const r=Q('select planned,actual from perf where bcc=? and actual is not null and planned>0 order by oid desc limit 5',b);return r.length?Math.min(1.15,Math.max(.85,r.reduce((s,x)=>s+x.actual/x.planned,0)/r.length)):1};
function learning(u){const bl=BCCS.filter(b=>u.role=='BCC'?b[0]==u.scope:u.role=='CRC'?b[1]==u.scope:true).map(b=>{const r=Q('select * from perf where bcc=? and actual is not null order by oid',b[0]),tg=r.reduce((s,x)=>s+x.target,0);return{bcc:b[0],orders:r.length,planErr:r.length?r1(r.reduce((s,x)=>s+Math.abs(x.actual-x.planned),0)/r.length):null,lastErr:r.length?r1(Math.abs(r.at(-1).actual-r.at(-1).planned)):null,exec:tg?Math.round(100*r.reduce((s,x)=>s+x.actual,0)/tg):null,factor:Math.round(learnFactor(b[0])*100)/100}});return{bcc:bl,learnedFeeders:Q('select count(*) n from feeders where est is not null')[0].n}}
const jf=h=>.78+.22*Math.exp(-((h-20)**2)/18)+.06*Math.exp(-((h-12)**2)/20);
let SIT={demand:4500,gen:4500,ic:0,trip:0};
const dem=h=>SIT.demand*jf(h)/jf(19),avail=()=>SIT.gen-SIT.trip+SIT.ic;
function situation(){const J=[14,15,16,17,18,19,20,21,22,23].map(h=>({h,deficit:Math.max(0,Math.round(dem(h)-avail()))})),fl=Q('select state,mw from flex');return{...SIT,deficit:Math.max(0,Math.round(dem(19)-avail())),plus30:Math.max(0,Math.round(dem(19.5)-avail())),j1:J,j1peak:Math.max(...J.map(x=>x.deficit)),flexAccepted:r1(fl.filter(x=>x.state=='Accepted').reduce((a,x)=>a+x.mw,0)),flexTotal:r1(fl.reduce((a,x)=>a+x.mw,0))}}
function planAlloc(D,am){const ref=steg(D),out={};for(const [crc,r] of Object.entries(ref)){let v=r.bcc;if(am=='FAIR'){const w=Q('select bcc,sum(mw) c from feeders where crc=? and crit=0 group by bcc',crc).map(x=>[x.bcc,x.c*(.5+bs(x.bcc)/100)]),T=w.reduce((a,x)=>a+x[1],0);v=Object.fromEntries(w.map(x=>[x[0],r1(r.mw*x[1]/T)]))}const ks=Object.keys(v),o={};let rest=r.mw;ks.forEach((n,i)=>{const x=i==ks.length-1?r1(rest):v[n];rest=r1(rest-x);o[n]=x});out[crc]={mw:r.mw,bcc:o}}return out}
function scenario(id,D,am,useFlex,fx){const conv=r1(Math.max(0,D-(useFlex?fx:0))),p=planAlloc(conv,am),caps=Object.fromEntries(Q('select bcc,sum(mw) c from feeders where crit=0 group by bcc').map(x=>[x.bcc,x.c])),pops=Object.fromEntries(Q('select bcc,sum(pop) p from cities group by bcc').map(x=>[x.bcc,x.p])),rows=[];
 for(const crc of ['North','South'])for(const [b,v] of Object.entries(p[crc].bcc))rows.push({bcc:b,crc,mw:v,cap:r1(caps[b]),ok:v<=caps[b]});const tot=rows.reduce((a,x)=>a+x.mw,0)||1;
 return{id,am,useFlex,flexMW:useFlex?fx:0,conventional:conv,north:p.North.mw,south:p.South.mw,bcc:rows,feasible:rows.every(x=>x.ok),consumers:Math.round(rows.reduce((a,x)=>a+pops[x.bcc]*Math.min(1,x.mw/caps[x.bcc]),0)),fairness:Math.round(rows.reduce((a,x)=>a+x.mw*bs(x.bcc),0)/tot),same:id=='B'&&!fx}}
const crcOf=b=>BCCS.find(x=>x[0]==b)[1],lvl=v=>v>=70?'g':v>=55?'y':v>=40?'o':'r';
const score=c=>{const h=Q('select du,d from hist where city=?',c.id),t=h.reduce((a,x)=>a+x.du,0),rec=h.filter(x=>x.d>=16).reduce((a,x)=>a+x.du,0),b=35*Math.min(1,t/300)+20*Math.min(1,h.length/8)+25*Math.min(1,rec/150)+10*(5-c.pr)/4+10*Math.min(1,c.pop/150000);return Math.round(100-b)};
const bs=b=>{const cs=Q('select * from cities where bcc=?',b);return cs.reduce((t,c)=>t+score(c),0)/cs.length};
function fairness(u){const all=Q('select * from cities').map(c=>({...c,s:score(c)})),v=all.filter(c=>u.role=='BCC'?c.bcc==u.scope:u.role=='CRC'?crcOf(c.bcc)==u.scope:true);return{national:Math.round(all.reduce((t,c)=>t+c.s,0)/all.length),cities:v.map(c=>{const h=Q('select du from hist where city=?',c.id);return{id:c.id,name:c.name,bcc:c.bcc,score:c.s,level:lvl(c.s),n:h.length,min:r1(h.reduce((t,x)=>t+x.du,0)),pr:c.pr}})}}
const sign=p=>{const b=Buffer.from(JSON.stringify(p)).toString('base64url');return b+'.'+crypto.createHmac('sha256',SECRET).update(b).digest('base64url')};
const verify=t=>{const [b,s]=(t||'').split('.');if(!b||!s)return null;const e=crypto.createHmac('sha256',SECRET).update(b).digest(),g=Buffer.from(s,'base64url');if(e.length!=g.length||!crypto.timingSafeEqual(e,g))return null;const p=JSON.parse(Buffer.from(b,'base64url'));return p.exp>Date.now()?p:null};
const sha=x=>crypto.createHash('sha256').update(x.join('|')).digest('hex');
const ev=(u,a,d='',oid)=>{const o=oid||(G("select id from orders where status in ('Allocated','Executing','Closing') order by id desc")||{}).id||null,p=(G('select h from events where h is not null order by id desc')||{}).h||'',ts=Date.now(),actor=u?u.name:'system',role=u?u.role:'SYSTEM';R('insert into events(ts,actor,role,action,detail,oid,h) values(?,?,?,?,?,?,?)',ts,actor,role,a,d,o,sha([p,ts,actor,role,a,d,o]))};
function verifyChain(){let p='',n=0;for(const e of Q('select * from events where h is not null order by id')){if(sha([p,e.ts,e.actor,e.role,e.action,e.detail,e.oid])!=e.h)return{ok:false,brokenAt:e.id,checked:n};p=e.h;n++}return{ok:true,checked:n}}
const flow=oid=>{const E=Q('select * from events where oid=? order by id',oid),by=a=>E.filter(e=>e.action==a).map(e=>({by:e.actor,ts:e.ts,detail:e.detail}));return{created:by('Order created')[0]||null,ack:by('Acknowledged'),accepted:by('Accepted'),refused:by('Refused'),executed:by('Execute'),restoration:by('Restoration ordered')[0]||null,completed:by('Order completed')[0]||null}};
const fail=(c,m)=>{throw{c,m}},need=(u,...r)=>{if(!u||!r.includes(u.role))fail(403,'Forbidden for role '+(u?u.role:'anonymous'))};
const el=f=>f.state=='OPEN'?mins(Date.now()-f.o):0,fresh=f=>Date.now()-f.seen<STALE_S*1000,active=()=>G("select * from orders where status in ('Allocated','Executing') order by id desc");
const vis=(u,f)=>u.role=='DN'||u.role=='ADMIN'||(u.role=='CRC'&&f.crc==u.scope)||(u.role=='BCC'&&f.bcc==u.scope);
const cand=f=>Q("select * from feeders where bcc=? and crit=0 and state='CLOSED' and cmd is null and id!=?",f.bcc,f.id).filter(fresh).sort((a,b)=>(Math.abs(a.mw-f.mw)+a.cum/20)-(Math.abs(b.mw-f.mw)+b.cum/20))[0];
let LINK=true;
const SH={North:.65,South:.35},TH=200,KEYS={North:{base:{Grombalia:.4,Sousse:.4,Beja:.2,Tunis:0},extra:{Tunis:.3,Grombalia:.25,Sousse:.3,Beja:.15}},South:{base:{Gafsa:.3,Sfax:.35,Gabes:.35},extra:{Gafsa:.2,Sfax:.4,Gabes:.4}}};
// STEG reference allocation: the first 200 MW (national) follows the base keys (Tunis spared); the part above 200 MW follows the extra keys.
const steg=D=>{const b=Math.min(D,TH),x=Math.max(0,D-TH),o={};for(const [c,sh] of Object.entries(SH)){const k=KEYS[c];o[c]={mw:r1(D*sh),bcc:Object.fromEntries(Object.keys(k.base).map(n=>[n,r1(sh*(b*k.base[n]+x*k.extra[n]))]))}}return o};
function allocate(o,am){const D=o.mw-(o.flex||0),ref=steg(D);R('delete from alloc where oid=?',o.id);
 for(const [crc,r] of Object.entries(ref)){R('insert into alloc values(?,?,?,?)',o.id,'CRC',crc,r.mw);let v=r.bcc;
  if(am=='FAIR'){const w=Q('select bcc,sum(mw) c from feeders where crc=? and crit=0 group by bcc',crc).map(x=>[x.bcc,x.c*(.5+bs(x.bcc)/100)]),T=w.reduce((a,x)=>a+x[1],0);v=Object.fromEntries(w.map(x=>[x[0],r1(r.mw*x[1]/T)]))}
  const ks=Object.keys(v);let rest=r.mw;ks.forEach((n,i)=>{const x=i==ks.length-1?r1(rest):v[n];rest=r1(rest-x);R('insert into alloc values(?,?,?,?)',o.id,'BCC',n,x)})}}
function kpi(u,fs,o,al){const mine=al.filter(a=>u.role=='BCC'?a.level=='BCC'&&a.name==u.scope:u.role=='CRC'?a.level=='CRC'&&a.name==u.scope:a.level=='CRC'),target=r1(mine.reduce((t,a)=>t+a.mw,0)),op=fs.filter(f=>f.state=='OPEN'),actual=r1(op.reduce((t,f)=>t+f.meas,0));
 return{target,actual,deviation:r1(target-actual),execution:target?Math.round(100*actual/target):0,open:op.length,maxDuration:r1(Math.max(0,...op.map(el))),rotations:fs.reduce((t,f)=>t+f.rot,0),alarms:fs.filter(f=>f.al==2).length,stale:fs.filter(f=>!fresh(f)).length,ens:r1(fs.reduce((t,f)=>t+f.ens+(f.state=='OPEN'?f.meas*el(f)/60:0),0)),responseMin:o&&o.first_open?r1(mins(o.first_open-o.ts)):null}}
function state(u){const o=active()||G('select * from orders order by id desc'),al=o?Q('select * from alloc where oid=?',o.id):[],fs=Q('select * from feeders order by id').filter(f=>vis(u,f));
 return{sit:u.role=='DN'||u.role=='ADMIN'?situation():null,flow:o?flow(o.id):null,learn:learning(u),sites:Q('select * from sites').filter(x=>{const f=G('select * from feeders where id=?',x.feeder);return f&&vis(u,f)}),fair:fairness(u),flex:u.role=='DN'||u.role=='ADMIN'?Q('select * from flex'):[],alerts:u.role=='ADMIN'?Q('select status,count(*) n from alerts group by status'):[],speed:SPEED,limit:LIM,warn:WARN,link:LINK,order:o,alloc:u.role=='BCC'?al.filter(a=>a.level=='BCC'&&a.name==u.scope):u.role=='CRC'?al.filter(a=>a.level=='CRC'&&a.name==u.scope||a.level=='BCC'&&fs.some(f=>f.bcc==a.name)):al,
  kpi:kpi(u,fs,o,al),feeders:fs.map(f=>({id:f.id,bcc:f.bcc,crc:f.crc,mw:f.mw,meas:r1(f.meas),prio:f.prio,crit:f.crit,state:f.state,elapsed:r1(el(f)),remaining:f.state=='OPEN'?r1(Math.max(0,LIM-el(f))):null,cum:r1(f.cum+el(f)),rot:f.rot,al:f.al,stale:!fresh(f),cmd:f.cmd,cand:f.state=='OPEN'&&f.al>=1&&u.role=='BCC'?(cand(f)||{}).id||null:null})),
  events:Q('select * from events order by id desc limit 40').filter(e=>u.role=='DN'||u.role=='ADMIN'||e.role!='BCC'||u.scope==''||e.actor.endsWith(u.scope.toLowerCase())||true)}}
const routes={
 'POST /api/login':(u,b)=>{const x=G('select * from users where name=?',b.user);if(!x)fail(401,'Bad credentials');const [s,h]=x.hash.split(':');if(hash(b.pass||'',s)!=x.hash)fail(401,'Bad credentials');ev(x,'Login');return{token:sign({name:x.name,role:x.role,scope:x.scope,exp:Date.now()+8*3600e3}),role:x.role,scope:x.scope,name:x.name}},
 'GET /api/state':u=>{need(u,'DN','ADMIN','CRC','BCC');return state(u)},
 'POST /api/orders':(u,b)=>{need(u,'DN');if(active())fail(409,'An order is already active');const am=b.am=='FAIR'?'FAIR':'STEG',fx=b.useFlex===false?0:G("select coalesce(sum(mw),0) s from flex where state='Accepted'").s,mw=+b.mw,cap=G('select sum(mw) c from feeders where crit=0').c;if(!(mw>0))fail(400,'mw required');if(mw>cap)fail(422,`Exceeds sheddable capacity (${r1(cap)} MW); critical feeders are protected`);
  const id=R('insert into orders(ts,by,mw,mode,status,flex,am) values(?,?,?,?,?,?,?)',Date.now(),u.name,mw,b.mode=='J1'?'J1':'RT','Allocated',fx,am).lastInsertRowid;allocate(G('select * from orders where id=?',id),am);if(fx)R("update flex set state='In use' where state='Accepted'");ev(u,'Order created',`${mw} MW${b.cause?' ('+b.cause+')':''} (${b.mode||'RT'}): flexibility ${fx} MW first, conventional ${r1(mw-fx)} MW allocation: ${am=='STEG'?'STEG reference keys (North 65% / South 35%, Tunis spared up to 200 MW)':'fairness-weighted'}`);return{id}},
 'POST /api/alloc':(u,b)=>{need(u,'CRC');const o=active();if(!o)fail(404,'No active order');const tgt=G("select mw from alloc where oid=? and level='CRC' and name=?",o.id,u.scope).mw,bl=Q("select name from alloc where oid=? and level='BCC' and name in (select bcc from feeders where crc=?)",o.id,u.scope).map(x=>x.name),sum=r1(bl.reduce((t,n)=>t+(+b.shares[n]||0),0));
  if(sum!=tgt)fail(409,`Consistency check failed: Σ BCC = ${sum} MW but CRC target is ${tgt} MW`);bl.forEach(n=>R("update alloc set mw=? where oid=? and level='BCC' and name=?",+b.shares[n],o.id,n));ev(u,'Allocation adjusted',JSON.stringify(b.shares));return{ok:1}},
 'POST /api/execute':u=>{need(u,'BCC');const o=active();if(!o)fail(404,'No active order');if(!flow(o.id).accepted.some(x=>x.detail==u.scope))fail(409,'Accept the order first: the CRC must acknowledge it, then the BCC accepts');const t=G("select mw from alloc where oid=? and level='BCC' and name=?",o.id,u.scope).mw;
  const fs=Q('select * from feeders where bcc=?',u.scope),cs=Object.fromEntries(Q('select * from cities where bcc=?',u.scope).map(c=>[c.id,score(c)])),st=Date.now()+15/SPEED*1000;const t2=t/learnFactor(u.scope);let sum=fs.filter(f=>f.state=='OPEN'||f.cmd=='OPEN'||f.plan).reduce((x,f)=>x+(f.est||f.mw),0),n=0,skipped=0;
  for(const f of fs.filter(f=>f.state=='CLOSED'&&!f.cmd&&!f.plan&&!f.crit).sort((a,b)=>cs[b.city]-cs[a.city]||a.cum-b.cum||b.prio-a.prio)){if(!fresh(f)){skipped++;continue}if(sum+(f.est||f.mw)<=t2*1.05){R('update feeders set plan=? where id=?',st,f.id);R('insert into alerts(city,oid,feeder,ts,start,status) values(?,?,?,?,?,?)',f.city,o.id,f.id,Date.now(),st,'Alert sent');sum+=f.est||f.mw;n++}}
  R('insert or replace into perf(oid,bcc,target,planned,actual) values(?,?,?,?,null)',o.id,u.scope,t,r1(sum));R("update orders set status='Executing' where id=?",o.id);const short=r1(t-sum);if(short>t*.05+.5)ev(u,'Shortfall',`${short} MW cannot be covered by BCC ${u.scope}: reported to CRC`);ev(u,'Execute',`target ${t} MW: ${n} feeders planned (fairest zones first), citizen alerts sent 15 min ahead${skipped?`, ${skipped} skipped (stale telemetry)`:''}`);return{commands:n,skipped,short}},
 'POST /api/rotate':(u,b)=>{need(u,'BCC');const f=G('select * from feeders where id=? and bcc=?',b.id,u.scope);if(!f||f.state!='OPEN')fail(404,'Open feeder not found');const c=cand(f);if(!c)fail(409,'No replacement candidate');R("update feeders set cmd='CLOSE' where id=?",f.id);R("update feeders set cmd='OPEN' where id=?",c.id);ev(u,'Rotation',`${f.id} → ${c.id}`);return{to:c.id}},
 'POST /api/command':(u,b)=>{need(u,'BCC');const f=G('select * from feeders where id=? and bcc=?',b.id,u.scope);if(!f)fail(404,'Feeder not found');if(b.cmd=='OPEN'&&f.crit)fail(403,'Protected site(s) on this feeder ('+(Q('select name from sites where feeder=?',f.id).map(x=>x.name).join(', ')||'critical feeder')+'): cut blocked');if(b.cmd=='OPEN'&&u.scope=='Tunis'){const o=active();if(!o||o.mw-(o.flex||0)<=TH)fail(403,'Tunis is spared until national shedding exceeds 200 MW')}if(!fresh(f))fail(409,'Stale telemetry: command refused');R('update feeders set cmd=? where id=?',b.cmd=='OPEN'?'OPEN':'CLOSE',f.id);ev(u,'Manual '+b.cmd,f.id);return{ok:1}},
 'POST /api/close':u=>{need(u,'DN');const o=active();if(!o)fail(404,'No active order');Q("select bcc,sum(meas) a from feeders where state='OPEN' group by bcc").forEach(x=>R('update perf set actual=? where oid=? and bcc=?',r1(x.a),o.id,x.bcc));R('update perf set actual=0 where oid=? and actual is null',o.id);R("update feeders set cmd='CLOSE' where state='OPEN'");R("update orders set status='Closing' where id=?",o.id);ev(u,'Restoration ordered',`order ${o.id}`);return{ok:1}},
 'POST /api/link':(u,b)=>{need(u,'ADMIN');LINK=!!b.up;ev(u,'SCADA link '+(LINK?'restored':'cut (simulated)'));return{link:LINK}},
 'GET /api/citizen':u=>{need(u,'CIT');const c=G('select * from cities where id=?',+u.scope),z=G('select * from citizens where user=?',u.name),h=Q('select du from hist where city=?',c.id),al=Q('select * from alerts where city=? order by id desc limit 8',c.id),sc=score(c);return{city:c.name,bcc:c.bcc,channel:z.channel,score:sc,level:lvl(sc),outages:h.length,minutes:r1(h.reduce((t,x)=>t+x.du,0)),supply:Q("select 1 x from feeders where city=? and state='OPEN'",c.id).length?'Interrupted':al.some(a=>a.status=='Alert sent')?'Interruption announced':'Normal',alerts:al.map(a=>({status:a.status,in:r1(Math.max(0,mins(a.start-Date.now()))),feeder:a.feeder,cause:'Temporary supply-demand balancing',est:LIM+' min max'}))}},
 'GET /api/industrial':u=>{need(u,'IND');return G('select * from flex where id=?',u.scope)},
 'POST /api/flex/request':(u,b)=>{need(u,'DN');R("update flex set state='Requested' where id=? and state in ('Available','Declined')",b.id);ev(u,'Flexibility requested',b.id);return{ok:1}},
 'POST /api/flex/respond':(u,b)=>{need(u,'IND');const f=G('select * from flex where id=?',u.scope);if(b.offer){R("update flex set state='Offered',omw=?,odur=?,msg=? where id=?",+b.offer.mw,+b.offer.dur,String(b.offer.msg||''),f.id);ev(u,'Flexibility offer',`${b.offer.mw} MW for ${b.offer.dur} min`)}else{R('update flex set state=? where id=?',b.accept?'Accepted':'Declined',f.id);ev(u,b.accept?'Flexibility accepted':'Flexibility declined',f.name)}return{ok:1}},
 'POST /api/flex/decide':(u,b)=>{need(u,'DN');R(b.accept?"update flex set state='Accepted',mw=omw,dur=odur where id=? and state='Offered'":"update flex set state='Declined' where id=? and state='Offered'",b.id);ev(u,'Offer '+(b.accept?'accepted':'declined'),b.id);return{ok:1}},
 'POST /api/accept':(u,b)=>{need(u,'CRC','BCC');const o=active();if(!o)fail(404,'No active order');const f=flow(o.id),a=b.ok===false?'Refused':null,why=b.reason?': '+b.reason:'';
  if(u.role=='CRC'){if(f.ack.some(x=>x.detail==u.scope))fail(409,'Already acknowledged');ev(u,a||'Acknowledged',u.scope+why)}
  else{if(!f.ack.some(x=>x.detail==crcOf(u.scope)))fail(409,`CRC ${crcOf(u.scope)} must acknowledge first`);if(f.accepted.some(x=>x.detail==u.scope))fail(409,'Already accepted');ev(u,a||'Accepted',u.scope+why)}return{ok:1}},
 'GET /api/history':u=>{need(u,'DN','ADMIN','CRC','BCC');return{orders:Q('select * from orders order by id desc limit 15').map(o=>({...o,...flow(o.id)})),integrity:verifyChain()}},
 'GET /api/audit/verify':u=>{need(u,'DN','ADMIN');return verifyChain()},
 'POST /api/sites':(u,b)=>{need(u,'ADMIN');const f=G('select * from feeders where id=?',b.feeder);if(!f||!b.name)fail(400,'A name and an existing feeder are required');R('insert into sites(name,type,feeder,by,ts) values(?,?,?,?,?)',String(b.name),String(b.type||'Other'),f.id,u.name,Date.now());R('update feeders set crit=1 where id=?',f.id);if(f.state=='OPEN'||f.cmd=='OPEN'||f.plan)R("update feeders set cmd='CLOSE',plan=null where id=?",f.id);ev(u,'Protected site registered',`${b.type||'Other'} "${b.name}" on ${f.id}: feeder is now protected${f.state=='OPEN'?' and is being restored':''}`);return{ok:1}},
 'POST /api/sites/remove':(u,b)=>{need(u,'ADMIN');const x=G('select * from sites where id=?',+b.id);if(!x)fail(404,'Site not found');if(String(b.reason||'').length<5)fail(400,'A written reason is required to remove a protection');R('delete from sites where id=?',x.id);if(!G('select 1 y from sites where feeder=?',x.feeder))R('update feeders set crit=0 where id=?',x.feeder);ev(u,'Protected site removed',`"${x.name}" on ${x.feeder}. Reason: ${b.reason}`);return{ok:1}},
 'GET /api/situation':u=>{need(u,'DN','ADMIN');return situation()},
 'POST /api/situation':(u,b)=>{need(u,'DN');const n=(v,d)=>v!=null&&v!==''&&Number.isFinite(+v)&&+v>=0?+v:d;SIT={demand:n(b.demand,SIT.demand),gen:n(b.gen,SIT.gen),ic:n(b.ic,SIT.ic),trip:n(b.trip,SIT.trip)};const z=situation();ev(u,'Situation updated',`demand ${SIT.demand}, generation ${SIT.gen}, interconnections ${SIT.ic}, unit outage ${SIT.trip} MW → deficit ${z.deficit} MW`);return z},
 'POST /api/scenarios':(u,b)=>{need(u,'DN','ADMIN');const z=situation(),D=Math.round(+b.mw||z.deficit),fx=z.flexAccepted;if(!(D>0))return{deficit:0,situation:z,scenarios:[],recommended:null,fairer:null};
  const sc=[scenario('A',D,'STEG',false,fx),scenario('B',D,'STEG',true,fx),scenario('C',D,'FAIR',true,fx)];let rec=fx>0?'B':'A';if(!sc.find(x=>x.id==rec).feasible)rec=(sc.find(x=>x.feasible)||sc[0]).id;const r=sc.find(x=>x.id==rec),best=sc.filter(x=>x.feasible).reduce((m,x)=>x.fairness>m.fairness?x:m,r);
  return{deficit:D,situation:z,scenarios:sc,recommended:rec,fairer:best.id!=rec&&best.fairness-r.fairness>=3?{id:best.id,delta:best.fairness-r.fairness}:null}},
 'POST /api/reference':(u,b)=>{need(u,'DN','ADMIN','CRC','BCC');return steg(+b.mw)},
 'GET /api/report':u=>{need(u,'DN','ADMIN');return{events:Q('select * from events order by id'),feeders:Q('select id,bcc,mw,state,cum,rot,ens from feeders'),orders:Q('select * from orders')}}};
function scada(path,method,b){if(method=='GET'&&path=='/api/scada/commands')return{link:LINK,feeders:Q('select id,mw from feeders'),cmds:Q('select id,cmd from feeders where cmd is not null')};
 if(method=='POST'&&path=='/api/scada/telemetry'){for(const m of b){const f=G('select * from feeders where id=?',m.id);if(!f)continue;R('update feeders set meas=?,seen=? where id=?',m.mw,Date.now(),f.id);
  if(m.breaker=='OPEN'&&f.state!='OPEN'){R("update feeders set state='OPEN',o=?,al=0,cmd=null where id=?",Date.now(),f.id);ev(null,'Breaker OPEN',`${f.id} ${m.mw} MW, timer started`);R("update alerts set status='In progress' where feeder=? and status='Alert sent'",f.id);const o=active();if(o&&!o.first_open)R('update orders set first_open=? where id=?',Date.now(),o.id)}
  if(m.breaker=='CLOSED'&&f.state=='OPEN'){const e=el(f);R("update feeders set state='CLOSED',o=null,cum=cum+?,ens=ens+?,rot=rot+1,al=0,cmd=null where id=?",e,f.meas*e/60,f.id);ev(null,'Breaker CLOSED',`${f.id} restored after ${r1(e)} min`);R('update feeders set est=? where id=?',r1(f.est?f.est*.7+f.meas*.3:f.meas),f.id);const c=G('select * from cities where id=?',f.city);R('insert into hist(city,d,du,cons) values(?,?,?,?)',f.city,23,r1(e),Math.round(c.pop*f.mw/c.dem));R("update alerts set status='Restored' where feeder=? and status='In progress'",f.id)}
  if(m.breaker=='CLOSED'&&f.cmd=='CLOSE')R('update feeders set cmd=null where id=?',f.id)}return{ok:1}}}
const srv=http.createServer((q,s)=>{const send=(c,j)=>{s.writeHead(c,{'content-type':'application/json'});s.end(JSON.stringify(j))};let d='';q.on('data',c=>d+=c);q.on('end',()=>{try{const p=new URL(q.url,'http://x').pathname,b=d?JSON.parse(d):{};
 if(p.startsWith('/api/scada/')){if(q.headers['x-api-key']!=KEY)fail(401,'Bad API key');const r=scada(p,q.method,b);if(!r)fail(404,'Not found');return send(200,r)}
 const h=routes[q.method+' '+p];if(h){const u=verify((q.headers.authorization||'').slice(7));if(p!='/api/login'&&!u)fail(401,'Login required');return send(200,h(u,b))}
 const f=p=='/'?'index.html':p.slice(1);if(/^[\w.-]+$/.test(f)&&fs.existsSync('public/'+f)){s.writeHead(200,{'content-type':f.endsWith('.html')?'text/html':'text/plain'});return s.end(fs.readFileSync('public/'+f))}fail(404,'Not found')}catch(e){send(e.c||500,{error:e.m||String(e)})}})});
const wss=new WebSocketServer({server:srv});let staleSeen=false;
setInterval(()=>{for(const f of Q('select * from feeders where plan is not null and plan<=?',Date.now()))R(f.crit?"update feeders set plan=null where id=?":"update feeders set cmd='OPEN',plan=null where id=?",f.id);for(const f of Q("select * from feeders where state='OPEN'")){const e=el(f);if(e>=LIM&&f.al<2){R('update feeders set al=2 where id=?',f.id);ev(null,'ALARM',`${f.id} exceeded ${LIM} min (${r1(e)} min), rotation required`)}else if(e>=WARN&&f.al<1){R('update feeders set al=1 where id=?',f.id);ev(null,'Warning',`${f.id} at ${r1(e)} min, limit ${LIM}`)}}
 const st=Q('select * from feeders').some(f=>!fresh(f));if(st!=staleSeen){staleSeen=st;ev(null,st?'Telemetry lost':'Telemetry restored',st?'Data marked STALE, commands on stale feeders are refused':'')}
 const o=G("select * from orders where status='Closing' order by id desc");if(o&&!G("select 1 x from feeders where state='OPEN' or cmd is not null")){ev(null,'Order completed','all feeders restored',o.id);R("update orders set status='Done' where id=?",o.id);R("update flex set state='Available' where state='In use'")}
 wss.clients.forEach(c=>c.readyState==1&&c.send('update'))},1000);
srv.listen(PORT,()=>console.log(`GRIDBALANCE API on :${PORT} (1 s = ${SPEED} sim-min, demo password "${PASS}")`));
